// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwikoueeo9HKngTxTytjed-rhCnJ9obQw',
    appId: '1:744914434624:web:bef2e52521e1264e5d3da5',
    messagingSenderId: '744914434624',
    projectId: 'final-mobile-cc765',
    authDomain: 'final-mobile-cc765.firebaseapp.com',
    storageBucket: 'final-mobile-cc765.firebasestorage.app',
    measurementId: 'G-FT8N0FV5TE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG6giq0BD0hJdSEvyVnUlEbLK7u1Wh2Vw',
    appId: '1:744914434624:android:c7b5a908c806d6015d3da5',
    messagingSenderId: '744914434624',
    projectId: 'final-mobile-cc765',
    storageBucket: 'final-mobile-cc765.firebasestorage.app',
  );
}
